package verbodavida.entities;
// Generated Aug 17, 2017 7:14:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ClassificacaoMembro generated by hbm2java
 */
@Entity
@Table(name="classificacao_membro"
    ,schema="public"
)
public class ClassificacaoMembro  implements java.io.Serializable {


     private long idclassificacaoMembro;
     private Ministerio ministerio;
     private String descricao;
     private Set<VinculoPessoaGrupo> vinculoPessoaGrupos = new HashSet<VinculoPessoaGrupo>(0);

    public ClassificacaoMembro() {
    }

	
    public ClassificacaoMembro(long idclassificacaoMembro, Ministerio ministerio) {
        this.idclassificacaoMembro = idclassificacaoMembro;
        this.ministerio = ministerio;
    }
    public ClassificacaoMembro(long idclassificacaoMembro, Ministerio ministerio, String descricao, Set<VinculoPessoaGrupo> vinculoPessoaGrupos) {
       this.idclassificacaoMembro = idclassificacaoMembro;
       this.ministerio = ministerio;
       this.descricao = descricao;
       this.vinculoPessoaGrupos = vinculoPessoaGrupos;
    }
   
     @Id 
     @GeneratedValue(strategy = GenerationType.IDENTITY)
    
    @Column(name="idclassificacao_membro", unique=true, nullable=false)
    public long getIdclassificacaoMembro() {
        return this.idclassificacaoMembro;
    }
    
    public void setIdclassificacaoMembro(long idclassificacaoMembro) {
        this.idclassificacaoMembro = idclassificacaoMembro;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ministerio_idministerio", nullable=false)
    public Ministerio getMinisterio() {
        return this.ministerio;
    }
    
    public void setMinisterio(Ministerio ministerio) {
        this.ministerio = ministerio;
    }

    
    @Column(name="descricao")
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="classificacaoMembro")
    public Set<VinculoPessoaGrupo> getVinculoPessoaGrupos() {
        return this.vinculoPessoaGrupos;
    }
    
    public void setVinculoPessoaGrupos(Set<VinculoPessoaGrupo> vinculoPessoaGrupos) {
        this.vinculoPessoaGrupos = vinculoPessoaGrupos;
    }




}


