package verbodavida.entities;
// Generated Aug 17, 2017 7:14:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Contato generated by hbm2java
 */
@Entity
@Table(name="contato"
    ,schema="public"
)
public class Contato  implements java.io.Serializable {


     private long idcontato;
     private String celular;
     private String celulartwo;
     private String telefone;
     private String telefonetwo;
     private String email;
     private Set<Pessoa> pessoas = new HashSet<Pessoa>(0);

    public Contato() {
    }

	
    public Contato(long idcontato) {
        this.idcontato = idcontato;
    }
    public Contato(long idcontato, String celular, String celulartwo, String telefone, String telefonetwo, String email, Set<Pessoa> pessoas) {
       this.idcontato = idcontato;
       this.celular = celular;
       this.celulartwo = celulartwo;
       this.telefone = telefone;
       this.telefonetwo = telefonetwo;
       this.email = email;
       this.pessoas = pessoas;
    }
   
     @Id 

     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="idcontato", unique=true, nullable=false)
    public long getIdcontato() {
        return this.idcontato;
    }
    
    public void setIdcontato(long idcontato) {
        this.idcontato = idcontato;
    }

    
    @Column(name="celular", length=30)
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }

    
    @Column(name="celulartwo", length=30)
    public String getCelulartwo() {
        return this.celulartwo;
    }
    
    public void setCelulartwo(String celulartwo) {
        this.celulartwo = celulartwo;
    }

    
    @Column(name="telefone", length=30)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    
    @Column(name="telefonetwo", length=30)
    public String getTelefonetwo() {
        return this.telefonetwo;
    }
    
    public void setTelefonetwo(String telefonetwo) {
        this.telefonetwo = telefonetwo;
    }

    
    @Column(name="email", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contato")
    public Set<Pessoa> getPessoas() {
        return this.pessoas;
    }
    
    public void setPessoas(Set<Pessoa> pessoas) {
        this.pessoas = pessoas;
    }




}


