package verbodavida.entities;
// Generated Jun 26, 2017 9:14:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Contato generated by hbm2java
 */
@Entity
@Table(name="contato"
    ,schema="public"
)
public class Contato  implements java.io.Serializable {


     private int idcontato;
     private String celular;
     private String celular2;
     private String telefone;
     private String telefone2;
     private String email;
     private Set<Pessoa> pessoas = new HashSet<Pessoa>(0);

    public Contato() {
    }

	
    public Contato(int idcontato) {
        this.idcontato = idcontato;
    }
    public Contato(int idcontato, String celular, String celular2, String telefone, String telefone2, String email, Set<Pessoa> pessoas) {
       this.idcontato = idcontato;
       this.celular = celular;
       this.celular2 = celular2;
       this.telefone = telefone;
       this.telefone2 = telefone2;
       this.email = email;
       this.pessoas = pessoas;
    }
   
     @Id 

    
    @Column(name="idcontato", unique=true, nullable=false)
    public int getIdcontato() {
        return this.idcontato;
    }
    
    public void setIdcontato(int idcontato) {
        this.idcontato = idcontato;
    }

    
    @Column(name="celular", length=30)
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }

    
    @Column(name="celular2", length=30)
    public String getCelular2() {
        return this.celular2;
    }
    
    public void setCelular2(String celular2) {
        this.celular2 = celular2;
    }

    
    @Column(name="telefone", length=30)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    
    @Column(name="telefone2", length=30)
    public String getTelefone2() {
        return this.telefone2;
    }
    
    public void setTelefone2(String telefone2) {
        this.telefone2 = telefone2;
    }

    
    @Column(name="email", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contato")
    public Set<Pessoa> getPessoas() {
        return this.pessoas;
    }
    
    public void setPessoas(Set<Pessoa> pessoas) {
        this.pessoas = pessoas;
    }




}


