package verbodavida.entities;
// Generated Jun 26, 2017 9:14:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Endereco generated by hbm2java
 */
@Entity
@Table(name="endereco"
    ,schema="public"
)
public class Endereco  implements java.io.Serializable {


     private int idendereco;
     private String rua;
     private Integer numero;
     private String cep;
     private String bairro;
     private String complemento;
     private Set<Pessoa> pessoas = new HashSet<Pessoa>(0);

    public Endereco() {
    }

	
    public Endereco(int idendereco) {
        this.idendereco = idendereco;
    }
    public Endereco(int idendereco, String rua, Integer numero, String cep, String bairro, String complemento, Set<Pessoa> pessoas) {
       this.idendereco = idendereco;
       this.rua = rua;
       this.numero = numero;
       this.cep = cep;
       this.bairro = bairro;
       this.complemento = complemento;
       this.pessoas = pessoas;
    }
   
     @Id 

    
    @Column(name="idendereco", unique=true, nullable=false)
    public int getIdendereco() {
        return this.idendereco;
    }
    
    public void setIdendereco(int idendereco) {
        this.idendereco = idendereco;
    }

    
    @Column(name="rua", length=50)
    public String getRua() {
        return this.rua;
    }
    
    public void setRua(String rua) {
        this.rua = rua;
    }

    
    @Column(name="numero")
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }

    
    @Column(name="cep", length=10)
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }

    
    @Column(name="bairro", length=50)
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    
    @Column(name="complemento", length=30)
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="endereco")
    public Set<Pessoa> getPessoas() {
        return this.pessoas;
    }
    
    public void setPessoas(Set<Pessoa> pessoas) {
        this.pessoas = pessoas;
    }




}


