package verbodavida.entities;
// Generated Jun 26, 2017 9:14:43 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Escala generated by hbm2java
 */
@Entity
@Table(name="escala"
    ,schema="public"
)
public class Escala  implements java.io.Serializable {


     private int idescala;
     private long grupoHasPessoaPessoaIdpessoa;
     private long grupoHasPessoaGrupoIdgrupo;
     private Date dataescala;

    public Escala() {
    }

	
    public Escala(int idescala, long grupoHasPessoaPessoaIdpessoa, long grupoHasPessoaGrupoIdgrupo) {
        this.idescala = idescala;
        this.grupoHasPessoaPessoaIdpessoa = grupoHasPessoaPessoaIdpessoa;
        this.grupoHasPessoaGrupoIdgrupo = grupoHasPessoaGrupoIdgrupo;
    }
    public Escala(int idescala, long grupoHasPessoaPessoaIdpessoa, long grupoHasPessoaGrupoIdgrupo, Date dataescala) {
       this.idescala = idescala;
       this.grupoHasPessoaPessoaIdpessoa = grupoHasPessoaPessoaIdpessoa;
       this.grupoHasPessoaGrupoIdgrupo = grupoHasPessoaGrupoIdgrupo;
       this.dataescala = dataescala;
    }
   
     @Id 

    
    @Column(name="idescala", unique=true, nullable=false)
    public int getIdescala() {
        return this.idescala;
    }
    
    public void setIdescala(int idescala) {
        this.idescala = idescala;
    }

    
    @Column(name="grupo_has_pessoa_pessoa_idpessoa", nullable=false)
    public long getGrupoHasPessoaPessoaIdpessoa() {
        return this.grupoHasPessoaPessoaIdpessoa;
    }
    
    public void setGrupoHasPessoaPessoaIdpessoa(long grupoHasPessoaPessoaIdpessoa) {
        this.grupoHasPessoaPessoaIdpessoa = grupoHasPessoaPessoaIdpessoa;
    }

    
    @Column(name="grupo_has_pessoa_grupo_idgrupo", nullable=false)
    public long getGrupoHasPessoaGrupoIdgrupo() {
        return this.grupoHasPessoaGrupoIdgrupo;
    }
    
    public void setGrupoHasPessoaGrupoIdgrupo(long grupoHasPessoaGrupoIdgrupo) {
        this.grupoHasPessoaGrupoIdgrupo = grupoHasPessoaGrupoIdgrupo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataescala", length=13)
    public Date getDataescala() {
        return this.dataescala;
    }
    
    public void setDataescala(Date dataescala) {
        this.dataescala = dataescala;
    }




}


