package verbodavida.entities;
// Generated Aug 17, 2017 7:14:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Grupo generated by hbm2java
 */
@Entity
@Table(name="grupo"
    ,schema="public"
)
public class Grupo  implements java.io.Serializable {


     private long idgrupo;
     private Ministerio ministerio;
     private String nome;
     private String descricao;
     private Set<VinculoPessoaGrupo> vinculoPessoaGrupos = new HashSet<VinculoPessoaGrupo>(0);

    public Grupo() {
    }

	
    public Grupo(long idgrupo, Ministerio ministerio) {
        this.idgrupo = idgrupo;
        this.ministerio = ministerio;
    }
    public Grupo(long idgrupo, Ministerio ministerio, String nome, String descricao, Set<VinculoPessoaGrupo> vinculoPessoaGrupos) {
       this.idgrupo = idgrupo;
       this.ministerio = ministerio;
       this.nome = nome;
       this.descricao = descricao;
       this.vinculoPessoaGrupos = vinculoPessoaGrupos;
    }
   
     @Id 

     @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="idgrupo", unique=true, nullable=false)
    public long getIdgrupo() {
        return this.idgrupo;
    }
    
    public void setIdgrupo(long idgrupo) {
        this.idgrupo = idgrupo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ministerio_idministerio", nullable=false)
    public Ministerio getMinisterio() {
        return this.ministerio;
    }
    
    public void setMinisterio(Ministerio ministerio) {
        this.ministerio = ministerio;
    }

    
    @Column(name="nome", length=50)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="descricao")
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="grupo")
    public Set<VinculoPessoaGrupo> getVinculoPessoaGrupos() {
        return this.vinculoPessoaGrupos;
    }
    
    public void setVinculoPessoaGrupos(Set<VinculoPessoaGrupo> vinculoPessoaGrupos) {
        this.vinculoPessoaGrupos = vinculoPessoaGrupos;
    }




}


