package verbodavida.entities;
// Generated Jun 26, 2017 9:14:43 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ministerio generated by hbm2java
 */
@Entity
@Table(name="ministerio"
    ,schema="public"
)
public class Ministerio  implements java.io.Serializable {


     private int idministerio;
     private String nome;
     private String descricao;
     private Set<Grupo> grupos = new HashSet<Grupo>(0);

    public Ministerio() {
    }

	
    public Ministerio(int idministerio) {
        this.idministerio = idministerio;
    }
    public Ministerio(int idministerio, String nome, String descricao, Set<Grupo> grupos) {
       this.idministerio = idministerio;
       this.nome = nome;
       this.descricao = descricao;
       this.grupos = grupos;
    }
   
     @Id 

    
    @Column(name="idministerio", unique=true, nullable=false)
    public int getIdministerio() {
        return this.idministerio;
    }
    
    public void setIdministerio(int idministerio) {
        this.idministerio = idministerio;
    }

    
    @Column(name="nome", length=40)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="descricao")
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ministerio")
    public Set<Grupo> getGrupos() {
        return this.grupos;
    }
    
    public void setGrupos(Set<Grupo> grupos) {
        this.grupos = grupos;
    }




}


