package verbodavida.entities;
// Generated Jun 26, 2017 9:14:43 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pessoa generated by hbm2java
 */
@Entity
@Table(name="pessoa"
    ,schema="public"
)
public class Pessoa  implements java.io.Serializable {


     private int idpessoa;
     private Contato contato;
     private Endereco endereco;
     private String nome;
     private String sobrenome;
     private Date datanascimento;

    public Pessoa() {
    }

	
    public Pessoa(int idpessoa, Contato contato, Endereco endereco) {
        this.idpessoa = idpessoa;
        this.contato = contato;
        this.endereco = endereco;
    }
    public Pessoa(int idpessoa, Contato contato, Endereco endereco, String nome, String sobrenome, Date datanascimento) {
       this.idpessoa = idpessoa;
       this.contato = contato;
       this.endereco = endereco;
       this.nome = nome;
       this.sobrenome = sobrenome;
       this.datanascimento = datanascimento;
    }
   
     @Id 

    
    @Column(name="idpessoa", unique=true, nullable=false)
    public int getIdpessoa() {
        return this.idpessoa;
    }
    
    public void setIdpessoa(int idpessoa) {
        this.idpessoa = idpessoa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="contato_idcontato", nullable=false)
    public Contato getContato() {
        return this.contato;
    }
    
    public void setContato(Contato contato) {
        this.contato = contato;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="endereco_idendereco", nullable=false)
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }

    
    @Column(name="nome", length=50)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="sobrenome", length=50)
    public String getSobrenome() {
        return this.sobrenome;
    }
    
    public void setSobrenome(String sobrenome) {
        this.sobrenome = sobrenome;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datanascimento", length=13)
    public Date getDatanascimento() {
        return this.datanascimento;
    }
    
    public void setDatanascimento(Date datanascimento) {
        this.datanascimento = datanascimento;
    }




}


