package verbodavida.entities;
// Generated Aug 17, 2017 7:14:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VinculoPessoaGrupo generated by hbm2java
 */
@Entity
@Table(name="vinculo_pessoa_grupo"
    ,schema="public"
)
public class VinculoPessoaGrupo  implements java.io.Serializable {


     private long idvinculoPessoaGrupo;
     private ClassificacaoMembro classificacaoMembro;
     private Grupo grupo;
     private Pessoa pessoa;
     private Date dataVinculacao;
     private Boolean ativo;
     private Set<Escala> escalas = new HashSet<Escala>(0);

    public VinculoPessoaGrupo() {
    }

	
    public VinculoPessoaGrupo(long idvinculoPessoaGrupo, ClassificacaoMembro classificacaoMembro, Grupo grupo, Pessoa pessoa) {
        this.idvinculoPessoaGrupo = idvinculoPessoaGrupo;
        this.classificacaoMembro = classificacaoMembro;
        this.grupo = grupo;
        this.pessoa = pessoa;
    }
    public VinculoPessoaGrupo(long idvinculoPessoaGrupo, ClassificacaoMembro classificacaoMembro, Grupo grupo, Pessoa pessoa, Date dataVinculacao, Boolean ativo, Set<Escala> escalas) {
       this.idvinculoPessoaGrupo = idvinculoPessoaGrupo;
       this.classificacaoMembro = classificacaoMembro;
       this.grupo = grupo;
       this.pessoa = pessoa;
       this.dataVinculacao = dataVinculacao;
       this.ativo = ativo;
       this.escalas = escalas;
    }
   
     @Id 
     @GeneratedValue(strategy = GenerationType.IDENTITY)
    
    @Column(name="idvinculo_pessoa_grupo", unique=true, nullable=false)
    public long getIdvinculoPessoaGrupo() {
        return this.idvinculoPessoaGrupo;
    }
    
    public void setIdvinculoPessoaGrupo(long idvinculoPessoaGrupo) {
        this.idvinculoPessoaGrupo = idvinculoPessoaGrupo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="classificacao_membro_idclassificacao_membro", nullable=false)
    public ClassificacaoMembro getClassificacaoMembro() {
        return this.classificacaoMembro;
    }
    
    public void setClassificacaoMembro(ClassificacaoMembro classificacaoMembro) {
        this.classificacaoMembro = classificacaoMembro;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="grupo_idgrupo", nullable=false)
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pessoa_idpessoa", nullable=false)
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data_vinculacao", length=29)
    public Date getDataVinculacao() {
        return this.dataVinculacao;
    }
    
    public void setDataVinculacao(Date dataVinculacao) {
        this.dataVinculacao = dataVinculacao;
    }

    
    @Column(name="ativo")
    public Boolean getAtivo() {
        return this.ativo;
    }
    
    public void setAtivo(Boolean ativo) {
        this.ativo = ativo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vinculoPessoaGrupo")
    public Set<Escala> getEscalas() {
        return this.escalas;
    }
    
    public void setEscalas(Set<Escala> escalas) {
        this.escalas = escalas;
    }




}


